server:
  port: 8080

spring:
  application:
    name: template-project
  redis:
    host: 192.168.18.134
    port: 6379
    #password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:create-db.sql
    data: classpath:demo-data.sql
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  jackson:
    default-property-inclusion: NON_NULL

mybatis:
#  type-aliases-package: com.example.domain.model
#  type-handlers-package: com.example.typehandler
  configuration:
    cache-enabled: false
    aggressive-lay-loading: false
    use-generated-keys: false
    auto-mapping-behavior: PARTIAL
    default-executor-type: REUSE
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    local-cache-scope: STATEMENT
    default-fetch-size: 100
    default-statement-timeout: 30