server:
  port: 8080

spring:
  application:
    name: template-project
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0ms
#    lettuce:
#      pool:
#        max-active: 8
#        min-idle: 0
#        max-idle: 0
#        max-wait: -1ms
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowPublicKeyRetrieval=true
      username: test
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 2000
  jackson:
    default-property-inclusion: NON_NULL

mybatis:
  configuration:
    cache-enabled: false
    aggressive-lay-loading: false
    use-generated-keys: false
    auto-mapping-behavior: PARTIAL
    default-executor-type: REUSE
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    local-cache-scope: STATEMENT
    default-fetch-size: 100
    default-statement-timeout: 30